import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const fetchData = async () => {
    const res = await fetch(`http://localhost:3000/api/hello`);
    const newData = await res.json();
    console.log(newData);
  };
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello</h1>
        <button onClick={fetchData}>Fetch Data</button>
      </main>
    </>
  );
}
